### ISSUE TITLE
En and es in route 

### ISSUE THREAD

**Issue by openqubit** [waqleh/codeigniter-language-in-url-internationalization#2]
I have noted that  en and es are generating an error if used together like below

$route['^(en|es|fr)$'] = $route['default_controller'];

if i visit a url like app/es/go/here i get app/en/es/go/here

**Comment by waqleh** [comment]
did you setup  $languages in MY_Lang.php properly? Also what you mentioned should only affect the default controller and not other controllers. Is  "go/here" you default controller?

**Comment by openqubit** [comment]
Yes, I did setup everything right. I have seen the same problem in meteor
js routes so its definitely a regex error.

**Comment by waqleh** [comment]
the URL are tying to access is incorrect. The language should be before the controller. 

> language/controller/method 


e.g.:
```
index.php/en/welcome/index
index.php/es/welcome/index
index.php/fr/welcome/index
```
