### ISSUE TITLE
routing problem

### ISSUE THREAD

**Issue by zzsolt87** [waqleh/codeigniter-language-in-url-internationalization#4]
When I try to add in my routing.php this: 
`$route['^(en|ar)/page/(:any)'] = "pages/page/$1";`
then in my Controller I get the 'en' instead of custom string(slug). I want to give a slug (example: about-us)

My Controller action function
`public function page($slug) `

**Comment by waqleh** [comment]
if you are getting `en` then you probably didn't setup `MY_Lang.php` properly, or other routes that you setup are conflicting with this one.

**Comment by zzsolt87** [comment]
My problem is: I can't change the route.  If I call with pages/page/about-us then work the page. about-us is a parameter(Slug). Pages a Controller where I have a page action function.
I want to change this route to page/slug, but when I put in route.php 
`$route['^(en|hu|ro|de|fr|nl)/page/(:any)'] = "pages/page/$1";` , and try to call with page/about-us, then I get a 404 page not found.

router.php
`
$route['default_controller'] = "home";


$route['admin'] = "admin/dashboard";
//$route['^(en|hu|ro|de|fr|nl)/projects$'] = "projects";
$route['^en/(.+)$'] = "$1";
$route['^hu/(.+)$'] = "$1";
$route['^ro/(.+)$'] = "$1";
$route['^de/(.+)$'] = "$1";
$route['^fr/(.+)$'] = "$1";
$route['^nl/(.+)$'] = "$1";

$route['^(en|hu|ro|de|fr|nl)$'] = $route['default_controller'];


$route['^(en|hu|ro|de|fr|nl)/page/(:any)'] = "pages/page/$1";

my changes in MY_Lang.php
`class MY_Lang extends CI_Lang {


    public $languages = [
        'en' => 'en',
        'ro' => 'ro',
        'hu' => 'hu',
        'de' => 'de',
        'fr' => 'fr',
        'nl' => 'nl'        
    ];


    public $special =  array ('admin','assets','editor');


    public $default_uri = '';


    public $default_lang_file = '/front_lang.php';
  `

**Comment by waqleh** [comment]
sorry for the late reply, better late than never, i see the problem you have, have you tried putting 
`$route['^(en|hu|ro|de|fr|nl)/page/(:any)'] = "pages/page/$1";`
above 
`$route['^en/(.+)$'] = "$1";`

this is explained in the readme file

**Comment by zzsolt87** [comment]
I changed my routes.php but for this request https:example.com/en/page/who-we-are the parameter what I get: en . I want to get who-we-are
 

    On Monday, December 10, 2018, 8:36:19 PM GMT+2, Walid <notifications@github.com> wrote:  
 
 
sorry for the late reply, better late than never, i see the problem you have, have you tried putting
$route['^(en|hu|ro|de|fr|nl)/page/(:any)'] = "pages/page/$1";
above
$route['^en/(.+)$'] = "$1";

**Comment by waqleh** [comment]
use "pages/page/$2" instead of "pages/page/$1" this is basic regular expression
