### ISSUE TITLE
Problem with empty lang redirect

### ISSUE THREAD

**Issue by howbizarre** [waqleh/codeigniter-language-in-url-internationalization#7]
Hello,
I'm not exactly PHP developer, but I have a some strange problem.

I have a local WAMP instalation of Apache 2.4 and PHP 7.2.

In MY_Lang.php on line 80 of the code `if ($this->is_special($segment))` always return true on adress like https://domain.com. This is very strange 'cos the problem does not exist in Firefox (Developer edition) but in Chrome base browsers.

I have change the line as `if ($segment != NULL && $this->is_special($segment))` and everything start working fine...

Is that good way to make the verification in PHP? I will use this code in production applications and trying to make it more stable in the future and easy to support.

**Comment by waqleh** [comment]
this is only intended for issues within this library, not php questions. php documentation or stackoverflow is what you are looking for, and no this is not good, this will result in notice error

**Comment by howbizarre** [comment]
> this is only intended for issues within this library, not php questions. php documentation or stackoverflow is what you are looking for, and no this is not good, this will result in notice error

Sorry...
Please remove the thread...
