### ISSUE TITLE
Default Language Route

### ISSUE THREAD

**Issue by sajumani** [waqleh/codeigniter-language-in-url-internationalization#8]
Hi,

Everything works superb as URL based Lang Switch; But  If somebody access url without language,  we need to redirect always to english URL.

example.com/  =>  example.com/en - **Not Working**
example.com/about => example.com/en/about  -  **Working**

Where can change that Or Is it missed feature ?

**Comment by waqleh** [comment]
you should be able to do this by setting `$default_uri` in `MY_Lang`
