### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by sajumani** [waqleh/codeigniter-language-in-url-internationalization#9]
Hi,

For custom routing, your method is working good.
I may have 25 Controllers, with more methods. 

All should i want to create as custom routes ?

We Could not pre-define, all my URLs in single line.

**Comment by waqleh** [comment]
no need to add all methods in routes, you will need a generic one, something like this:
```
$route['^en/(.+)$'] = "$1";
$route['^ar/(.+)$'] = "$1";
```

**Comment by sajumani** [comment]
It is not working...

Brings into 404 page
